### ISSUE TITLE
求助: hexo generate 出错: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by duchenpaul** [theme-shoka-x/hexo-theme-shokaX#108]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

执行`hexo algolia`和`hexo generate`出现大量错误

```
ERROR Script load failed: themes/shokaX/scripts/libtypes.d.ts
/src/themes/shokaX/scripts/libtypes.d.ts:1
(function(exports, require, module, __filename, __dirname, hexo){import type TemplateLocals from 'hexo'
                                                                 ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at createScript (node:vm:259:10)
    at runInThisContext (node:vm:307:10)
    at /src/node_modules/hexo/lib/hexo/index.js:303:18
    at tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/src/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/src/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/src/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
ERROR Script load failed: themes/shokaX/scripts/filters/locals.ts
/src/themes/shokaX/scripts/filters/locals.ts:7
hexo.extend.filter.register('template_locals', (locals:localsPlus) => {
                                                      ^

SyntaxError: Unexpected token ':'
    at new Script (node:vm:100:7)
    at createScript (node:vm:259:10)
    at runInThisContext (node:vm:307:10)
    at /src/node_modules/hexo/lib/hexo/index.js:303:18
    at tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/src/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/src/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/src/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
ERROR Script load failed: themes/shokaX/scripts/helpers/asset.ts
/src/themes/shokaX/scripts/helpers/asset.ts:3
import theme_env from '../../package.json'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (node:vm:100:7)
    at createScript (node:vm:259:10)
    at runInThisContext (node:vm:307:10)
    at /src/node_modules/hexo/lib/hexo/index.js:303:18
```

### 复现步骤

我使用的是下面的命令
```bash
cd /src
npm config set registry https://repo.nju.edu.cn/repository/npm/

# npm install
# npm un hexo-renderer-marked --save

## shokaX theme config
# shokax
npm i shokax-cli --location=global
/usr/local/bin/SXC install shokaX
## #####################

hexo algolia
hexo generate
```

### 相关配置

node --version
v20.2.0

hexo: 6.3.0
hexo-cli: 4.3.1
os: linux 5.10.0-22-amd64 Alpine Linux
node: 20.2.0
acorn: 8.8.2
ada: 2.4.0
ares: 1.19.0
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.0
icu: 73.1
llhttp: 8.1.0
modules: 115
napi: 8
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.8+quic
simdutf: 3.2.9
tz: 2023c
undici: 5.22.0
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.16
v8: 11.3.244

### 注意事项

- [x] 我已确认以上事项

**Comment by D-Sketon** [comment]
正常来说npm源应该是没有ts文件的，尝试将ts删掉试试

**Comment by duchenpaul** [comment]
是的, 我用以前的部署脚本, 它clone repo了, 实际上不需要clone, 去了就没有错了
