### ISSUE TITLE
求助: 渲染错误: TypeError: minimatch is not a function

### ISSUE THREAD

**Issue by duchenpaul** [theme-shoka-x/hexo-theme-shokaX#109]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

渲染的时候报错, 跟这个[issue](https://stackoverflow.com/questions/76049247/typeerror-minimatch-is-not-a-function-error-when-running-new-expo-project)有关?
```
...
info Direct dependencies
└─ hexo-renderer-multi-next-markdown-it@0.1.7
info All dependencies
└─ hexo-renderer-multi-next-markdown-it@0.1.7
Done in 178.99s.
INFO  hexo-renderer-multi-next-markdown-it installed
yarn add v1.22.19
[1/4] Resolving packages...
...
ERROR Render HTML failed: 2023/05/31/troubleshoot_windows_key_holding_problem/index.html
TypeError: minimatch is not a function
    at check_exclude (/src/node_modules/hexo-renderer-multi-next-markdown-it/lib/filter.js:20:11)
    at Hexo.logic_html (/src/node_modules/hexo-renderer-multi-next-markdown-it/lib/filter.js:38:7)
    at Hexo.tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/src/node_modules/bluebird/js/release/method.js:15:34)
    at /src/node_modules/hexo/lib/extend/filter.js:67:52
    at tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/src/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/src/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/src/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/src/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/src/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
ERROR Render HTML failed: 2023/04/13/docker-notes/index.html
TypeError: minimatch is not a function
    at check_exclude (/src/node_modules/hexo-renderer-multi-next-markdown-it/lib/filter.js:20:11)
    at Hexo.logic_html (/src/node_modules/hexo-renderer-multi-next-markdown-it/lib/filter.js:38:7)
    at Hexo.tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/src/node_modules/bluebird/js/release/method.js:15:34)
    at /src/node_modules/hexo/lib/extend/filter.js:67:52
    at tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/src/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/src/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/src/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/src/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/src/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/src/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/src/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/src/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/src/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/src/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
```

### 复现步骤

```
cd /src
npm config set registry https://repo.nju.edu.cn/repository/npm/

# npm install
# npm un hexo-renderer-marked --save

## shokaX theme config
# shokax
npm i shokax-cli --location=global
/usr/local/bin/SXC install shokaX
## #####################

hexo algolia
hexo generate
```

### 相关配置

node --version
v20.2.0

hexo-renderer-multi-next-markdown-it@0.1.7

hexo: 6.3.0
hexo-cli: 4.3.1
os: linux 5.10.0-22-amd64 Alpine Linux
node: 20.2.0
acorn: 8.8.2
ada: 2.4.0
ares: 1.19.0
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.0
icu: 73.1
llhttp: 8.1.0
modules: 115
napi: 8
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.8+quic
simdutf: 3.2.9
tz: 2023c
undici: 5.22.0
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.16
v8: 11.3.244

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
看样子是的
https://github.com/theme-shoka-x/hexo-renderer-multi-next-markdown-it/commit/596b054503a7f1484f1ff964ba08646a0a505e48 将minimatch升级到了v9
