### ISSUE TITLE
hexo g时报shokax_inject非函数错误

### ISSUE THREAD

**Issue by THB009** [theme-shoka-x/hexo-theme-shokaX#134]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

```
ERROR
TypeError: D:\my_real_blog\node_modules\hexo-theme-shokax\layout\_partials\layout.pug:14
    12|         != partial('_partials/head/head.pug', {}, {cache: true})
    13|         != partial('_partials/head/head_com.pug')
  > 14|         != shokax_inject('head')
    15|         title
    16|             block title
    17|                 != `${alternate?alternate + " = ":""}${title}${subtitle?" = "+subtitle:""}`

shokax_inject is not a function
    at eval (eval at wrap (D:\my_real_blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:763:46)
    at template (eval at wrap (D:\my_real_blog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1235:7)
    at _View._compiled (D:\my_real_blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\my_real_blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\my_real_blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\my_real_blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\my_real_blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\my_real_blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

### 复现步骤

```
$ hexo g
INFO  Validating config
INFO  Start processing
Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin.
INFO  minify the js: unknown.js [ 34.34% saved]
INFO  Files loaded in 1.13 s
ERROR
TypeError: D:\my_real_blog\node_modules\hexo-theme-shokax\layout\_partials\layout.pug:14
   //接上面的错误
```

### 相关配置

$ node --version
v18.17.0
$ hexo --version
INFO  Validating config
hexo: 6.3.0
hexo-cli: 4.3.1
os: win32 10.0.22621
node: 18.17.0
acorn: 8.8.2
ada: 2.5.0
ares: 1.19.1
brotli: 1.0.9
cldr: 43.0
icu: 73.1
llhttp: 6.0.11
modules: 108
napi: 9
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.9+quic
simdutf: 3.2.12
tz: 2023c
undici: 5.22.1
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.18
v8: 10.2.154.26-node.26
zlib: 1.2.13.1-motley

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
使用0.3预览版本地无法复现
删除对应npm包后重新安装，这个问题会再次出现吗

**Comment by THB009** [comment]
重新安装后，出现了新的错误，如下:
```
TypeError: D:\my_real_blog\node_modules\hexo-theme-shokaX\layout\_partials\layout.pug:128
    126|             != _new_comments('waline')
    127|
  > 128|         != shokax_inject('bodyEnd')
    129|
    130|
    131|

Cannot read properties of undefined (reading 'key') - could not read from D:\my_real_blog\node_modules\hexo-theme-shokaX\layout\inject\bodyEnd\loader.pug (ENOENT: no such file or directory, open 'D:\my_real_blog\node_modules\hexo-theme-shokaX\layout\inject\bodyEnd\loader.pug') on line 21
    at eval (eval at wrap (D:\my_real_blog\node_modules\.pnpm\pug-runtime@3.0.1\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:88:72)
    at template (eval at wrap (D:\my_real_blog\node_modules\.pnpm\pug-runtime@3.0.1\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:143:7)
    at _View._compiledSync (D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:59:25)
    at D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\plugins\helper\partial.js:31:52
    at Cache.apply (D:\my_real_blog\node_modules\.pnpm\hexo-util@2.7.0\node_modules\hexo-util\lib\cache.js:27:46)
    at Object.fragmentCache (D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\plugins\helper\fragment_cache.js:11:34)
    at Object.partial (D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\plugins\helper\partial.js:31:17)
    at D:\my_real_blog\node_modules\hexo-theme-shokaX\scripts\helpers\engine.js:142:27
    at Array.map (<anonymous>)
    at Object.<anonymous> (D:\my_real_blog\node_modules\hexo-theme-shokaX\scripts\helpers\engine.js:142:10)
    at eval (eval at wrap (D:\my_real_blog\node_modules\.pnpm\pug-runtime@3.0.1\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1193:46)
    at template (eval at wrap (D:\my_real_blog\node_modules\.pnpm\pug-runtime@3.0.1\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1194:7)
    at _View._compiled (D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\my_real_blog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at D:\my_real_blog\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\my_real_blog\node_modules\.pnpm\hexo@6.3.0\node_modules\hexo\lib\hexo\router.js:47:5)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by zkz098** [comment]
是否安装了qweather这个ShokaX插件，错误看起来可能和此插件有关

**Comment by THB009** [comment]
经确认，删除qweather插件后果然没有报错，应该就是qweather的问题

**Comment by zkz098** [comment]
可能是inject的偶发性问题，本地使用0.3预览+qweather并未出现此错误
