### ISSUE TITLE
(node:18310) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by couse1989** [theme-shoka-x/hexo-theme-shokaX#316]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [x] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

启动项目后访问主页终端有个属性弃用信息，但不影响

``` shell 
(base) bob@xperia:~/shokax-can$ node --trace-deprecation node_modules/hexo/bin/hexo s
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
(node:43770) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at res.setHeader (/home/bob/shokax-can/node_modules/.store/connect@2.7.11/node_modules/connect/lib/patch.js:48:14)
    at /home/bob/shokax-can/node_modules/.store/hexo-server@3.0.0/node_modules/hexo-server/lib/middlewares/header.js:8:9
    at call (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:239:7)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:183:5)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)
    at next (/home/bob/shokax-can/node_modules/.store/connect@3.7.0/node_modules/connect/index.js:161:14)

```
可以用 `node --no-deprecation node_modules/hexo/bin/hexo s` 或 `export NODE_NO_WARNINGS=1` 启动忽略这个警告

### 复现步骤

执行过cnpm update

### 相关配置

``` bash
(base) bob@xperia:~/shokax-can$ hexo -v
INFO  Validating config
hexo: 7.3.0
hexo-cli: 4.3.2
os: linux 6.5.0-44-generic Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
node: 20.16.0
acorn: 8.11.3
ada: 2.8.0
ares: 1.31.0
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 45.0
icu: 75.1
llhttp: 8.1.2
modules: 115
napi: 9
nghttp2: 1.61.0
nghttp3: 0.7.0
ngtcp2: 1.1.0
openssl: 3.0.13+quic
simdutf: 5.2.8
tz: 2024a
undici: 6.19.2
unicode: 15.1
uv: 1.46.0
uvwasi: 0.0.21
v8: 11.3.244.8-node.23
zlib: 1.3.0.1-motley-209717d
```
---
``` bash 
(base) bob@xperia:~/shokax-can$ cnpm list --depth=0
hexo-site@0.0.0 /home/bob/shokax-can
├── @algolia/client-search@4.24.0 -> ./node_modules/.store/@algolia+client-search@4.24.0/node_modules/@algolia/client-search
├── @babel/code-frame@7.24.7 extraneous -> ./node_modules/.store/@babel+code-frame@7.24.7/node_modules/@babel/code-frame
├── @babel/helper-string-parser@7.24.8 extraneous -> ./node_modules/.store/@babel+helper-string-parser@7.24.8/node_modules/@babel/helper-string-parser
├── @babel/helper-validator-identifier@7.24.7 extraneous -> ./node_modules/.store/@babel+helper-validator-identifier@7.24.7/node_modules/@babel/helper-validator-identifier
├── @babel/highlight@7.24.7 extraneous -> ./node_modules/.store/@babel+highlight@7.24.7/node_modules/@babel/highlight
├── @babel/parser@7.25.3 extraneous -> ./node_modules/.store/@babel+parser@7.25.3/node_modules/@babel/parser
├── @babel/runtime@7.25.0 extraneous -> ./node_modules/.store/@babel+runtime@7.25.0/node_modules/@babel/runtime
├── @babel/types@7.25.2 extraneous -> ./node_modules/.store/@babel+types@7.25.2/node_modules/@babel/types
├── @waline/client@3.3.0 -> ./node_modules/.store/@waline+client@3.3.0/node_modules/@waline/client
├── algoliasearch@4.24.0 -> ./node_modules/.store/algoliasearch@4.24.0/node_modules/algoliasearch
├── babel-walk@3.0.0-canary-5 extraneous -> ./node_modules/.store/babel-walk@3.0.0-canary-5/node_modules/babel-walk
├── esbuild@0.23.0 -> ./node_modules/.store/esbuild@0.23.0/node_modules/esbuild
├── hexo-admin@2.3.0 -> ./node_modules/.store/hexo-admin@2.3.0/node_modules/hexo-admin
├── hexo-algoliasearch@2.0.1 -> ./node_modules/.store/hexo-algoliasearch@2.0.1/node_modules/hexo-algoliasearch
├── hexo-feed@1.1.2 -> ./node_modules/.store/hexo-feed@1.1.2/node_modules/hexo-feed
├── hexo-fs@4.1.3 -> ./node_modules/.store/hexo-fs@4.1.3/node_modules/hexo-fs
├── hexo-generator-archive@2.0.0 -> ./node_modules/.store/hexo-generator-archive@2.0.0/node_modules/hexo-generator-archive
├── hexo-generator-category@2.0.0 -> ./node_modules/.store/hexo-generator-category@2.0.0/node_modules/hexo-generator-category
├── hexo-generator-index@4.0.0 -> ./node_modules/.store/hexo-generator-index@4.0.0/node_modules/hexo-generator-index
├── hexo-generator-tag@2.0.0 -> ./node_modules/.store/hexo-generator-tag@2.0.0/node_modules/hexo-generator-tag
├── hexo-pagination@4.0.0 -> ./node_modules/.store/hexo-pagination@4.0.0/node_modules/hexo-pagination
├── hexo-renderer-ejs@2.0.0 -> ./node_modules/.store/hexo-renderer-ejs@2.0.0/node_modules/hexo-renderer-ejs
├── hexo-renderer-multi-next-markdown-it@0.2.1 -> ./node_modules/.store/hexo-renderer-multi-next-markdown-it@0.2.1/node_modules/hexo-renderer-multi-next-markdown-it
├── hexo-renderer-pug@3.0.0 -> ./node_modules/.store/hexo-renderer-pug@3.0.0/node_modules/hexo-renderer-pug
├── hexo-renderer-stylus@3.0.1 -> ./node_modules/.store/hexo-renderer-stylus@3.0.1/node_modules/hexo-renderer-stylus
├── hexo-server@3.0.0 -> ./node_modules/.store/hexo-server@3.0.0/node_modules/hexo-server
├── hexo-theme-landscape@1.0.0 -> ./node_modules/.store/hexo-theme-landscape@1.0.0/node_modules/hexo-theme-landscape
├── hexo-theme-shokax@0.4.11 -> ./node_modules/.store/hexo-theme-shokax@0.4.11/node_modules/hexo-theme-shokax
├── hexo-util@3.3.0 -> ./node_modules/.store/hexo-util@3.3.0/node_modules/hexo-util
├── hexo@7.3.0 -> ./node_modules/.store/hexo@7.3.0/node_modules/hexo
├── instantsearch.js@4.73.2 -> ./node_modules/.store/instantsearch.js@4.73.2/node_modules/instantsearch.js
├── js-yaml@4.1.0 -> ./node_modules/.store/js-yaml@4.1.0/node_modules/js-yaml
├── mouse-firework@0.0.6 -> ./node_modules/.store/mouse-firework@0.0.6/node_modules/mouse-firework
├── quicklink@2.3.0 -> ./node_modules/.store/quicklink@2.3.0/node_modules/quicklink
├── theme-shokax-anime@0.0.7 -> ./node_modules/.store/theme-shokax-anime@0.0.7/node_modules/theme-shokax-anime
├── theme-shokax-pjax@0.0.3 -> ./node_modules/.store/theme-shokax-pjax@0.0.3/node_modules/theme-shokax-pjax
├── twikoo@1.6.38 -> ./node_modules/.store/twikoo@1.6.38/node_modules/twikoo
├── unlazy@0.11.3 -> ./node_modules/.store/unlazy@0.11.3/node_modules/unlazy
└── vue@3.4.32 -> ./node_modules/.store/vue@3.4.32/node_modules/vue

```
---`
``` bash
(base) bob@xperia:~/shokax-can$ node -v
v20.16.0
```

### 注意事项

- [X] 我已确认以上事项

**Comment by D-Sketon** [comment]
1. 这看似是hexo-server的问题
2. hexo-server@ 3.0.0应该依赖的是connect@ 3.7.0，不清楚你的这个connect@ 2是从哪里来的，可以看一下lock文件

**Comment by couse1989** [comment]
> 1. 这看似是hexo-server的问题
> 2. hexo-server@ 3.0.0应该依赖的是connect@ 3.7.0，不清楚你的这个connect@ 2是从哪里来的，可以看一下lock文件
.
lock文件的版本确实是3.7.0
``` shell 
(base) bob@xperia:~/shokax-can$ grep connect pnpm-lock.yaml
  connect@3.7.0:
  connect@3.7.0:
      connect: 3.7.0
```
