### ISSUE TITLE
_cover_index is not a function

### ISSUE THREAD

**Issue by clown-q** [theme-shoka-x/hexo-theme-shokaX#320]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题
- [ ] 为保证 Issue 及时得到回复，我已选择至少一名不在 busy 状态的组织成员作为`assignees`

### 问题发生位置

Hexo渲染报错

### 问题描述

Unhandled rejection TypeError: F:\blog\themes\shokax\layout\_partials\layout.pug:9
    7|     - ignores.push(theme.quicklink.ignores)
    8|
  > 9| - var covers = _cover_index(page, 6)
    10| - var enableFixedCover = theme.homeConfig?.fixedCover
    11|
    12| doctype html
    
_cover_index is not a function
    at eval (eval at wrap (F:\blog_clown\node_modules\.pnpm\pug-runtime@3.0.1\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:631:14)
    at template (eval at wrap (F:\blog_clown\node_modules\.pnpm\pug-runtime@3.0.1\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1187:7)
    at _View._compiled (F:\blog_clown\node_modules\.pnpm\hexo@7.3.0_chokidar@3.6.0\node_modules\hexo\dist\theme\view.js:120:67)
    at _View.render (F:\blog_clown\node_modules\.pnpm\hexo@7.3.0_chokidar@3.6.0\node_modules\hexo\dist\theme\view.js:37:21)
    at F:\blog_clown\node_modules\.pnpm\hexo@7.3.0_chokidar@3.6.0\node_modules\hexo\dist\hexo\index.js:60:29
    at tryCatcher (F:\blog_clown\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at F:\blog_clown\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\blog_clown\node_modules\.pnpm\hexo@7.3.0_chokidar@3.6.0\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:496:12)
    at resume_ (node:internal/streams/readable:999:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### 复现步骤

cd themes
git clone https://github.com/theme-shoka-x/hexo-theme-shokaX.git
cd shokax
node ./toolbox/compiler.mjs
cd ../..
hexo s 

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
编译完成之后`scripts`文件夹是不是空的

**Comment by clown-q** [comment]
我使用第一种临时解决了上面的问题，感谢

**Comment by zkz098** [comment]
0.4.13引入了基于esbuild的新型编译器，发布后此Issue可关闭
