### ISSUE TITLE
hexo algolia 出错

### ISSUE THREAD

**Issue by xiutz** [theme-shoka-x/hexo-theme-shokaX#55]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

前端渲染不正确(CSS错位或JS报错等)

### 问题描述

algolia已注册并配置，且在配置文件中已经配置好以下信息，其中title和path后面注释是必须配置，不理解需要进行什么操作
algolia:
  appId: （已改为对应的appID）#Your appId
  apiKey: （已改为对应的apiKey）#Your apiKey
  adminApiKey: （已改为对应的adminApiKey）#Your adminApiKey
  chunkSize: 5000
  indexName: shoka #"shokaX"
  fields:
    - title #必须配置
    - path #必须配置

### 复现步骤

$ hexo algolia
INFO  Validating config

E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\lib\algolia.js:154
    const fields = getBasicFields(algoliaConfig.fields);
                                                ^

TypeError: Cannot read properties of undefined (reading 'fields')
    at E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\lib\algolia.js:154:49
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\lib\algolia.js:14:103)
    at _next (E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\lib\algolia.js:16:194)
    at E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\lib\algolia.js:16:364
    at new Promise (<anonymous>)
    at E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\lib\algolia.js:16:97
    at algoliaCommand (E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\lib\algolia.js:203:17)
    at Hexo.<anonymous> (E:\WEB\WebName\rfid_wai\node_modules\hexo-algoliasearch\index.js:7:29)
    at Hexo.tryCatcher (E:\WEB\WebName\rfid_wai\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:13:39)
    at Hexo.call (E:\WEB\WebName\rfid_wai\node_modules\hexo\lib\hexo\index.js:258:27)
    at C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\lib\hexo.js:60:17
    at tryCatcher (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (C:\Users\85250\AppData\Roaming\npm\node_modules\hexo-cli\node_modules\bluebird\js\release\async.js:15:14)

### 相关配置

$ hexo version
INFO  Validating config
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.19044
node: 16.13.1
v8: 9.4.146.24-node.14
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.45.1
napi: 8
llhttp: 6.0.4
openssl: 1.1.1l+quic
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV

$ npm version
{
  'hexo-site': '0.0.0',
  npm: '8.1.2',
  node: '16.13.1',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

### 注意事项

- [X] 我已确认以上事项

**Comment by zkz098** [comment]
有点怪，看样子是配置根本没获取到
建议执行`hexo clean`后再次生成，如果仍然存在问题就需要测试了

**Comment by zkz098** [comment]
无法复现此问题

**Comment by D-Sketon** [comment]
是不是配置文件缩进有问题导致读取失败

**Comment by Zero-Ql** [comment]
我也遇到了相同的问题
请不要在 `_config.shoka.yml` 文件中编写 algolia 配置，正确位置应该是在 `_config.yml` 文件中添加
![image](https://github.com/theme-shoka-x/hexo-theme-shokaX/assets/113659032/79736eb8-54cf-44d9-a83e-decbecad1e78)
